### ISSUE TITLE
Ban type

### ISSUE THREAD

**Issue by ihosts3** [Alexr03/TCAdminBanManagement#1]
Hello,

When you ban someone, and choose the ban type as FTP the ban type after update is Web and the person is banned in web.

If you keep the ban and made F5 or back to home and goes again to ban management you will see the ban type is "ALL".

When the ban type is FTP:
https://prnt.ihosts3.com/65ijci53.gif

F5 or back to ban management page:
https://prnt.ihosts3.com/f81f5e3y.png

When the ban type is Web:
https://prnt.ihosts3.com/yxtzx97a.gif

Regards

**Comment by Alexr03** [comment]
Thanks for the report.
Fixed in 00fc13d
